FROM node:18.19-slim

ARG NODE_ENV
ARG NODE_S3_PUBLIC_URL
ARG NODE_DOMAIN
ARG NODE_EMAIL_HR
ARG NODE_EMAIL_CV
ARG NODE_EMAIL_CONTACT
ARG NODE_EMAIL_MARKETING
ARG NODE_SENTRY_DSN_FRONT
ARG NODE_PRISMIC_API
ARG NODE_IP_INFO_TOKEN
ARG NODE_SMARTLOOK_PROJECT_ID
ARG NODE_ANALYTICS_UNIVERSAL_KEY
ARG NODE_GA4_KEY
ARG NODE_SENDPULSE_ADDRESSBOOKS_ID
ARG FF_ENVIRONMENT
ARG RECAPTCHA_SITE_KEY
ARG MAD_MARKETING_BACKEND_API
ARG NUXT_PUBLIC_SITE_URL
ARG NITRO_PRESET
ARG NODE_SENTRY_LOADER_PATH

ENV NODE_ENV=${NODE_ENV}
ENV NODE_S3_PUBLIC_URL=${NODE_S3_PUBLIC_URL}
ENV NODE_DOMAIN=${NODE_DOMAIN}
ENV NODE_EMAIL_HR=${NODE_EMAIL_HR}
ENV NODE_EMAIL_CV=${NODE_EMAIL_CV}
ENV NODE_EMAIL_CONTACT=${NODE_EMAIL_CONTACT}
ENV NODE_EMAIL_MARKETING=${NODE_EMAIL_MARKETING}
ENV NODE_SENTRY_DSN_FRONT=${NODE_SENTRY_DSN_FRONT}
ENV NODE_PRISMIC_API=${NODE_PRISMIC_API}
ENV NODE_SMARTLOOK_PROJECT_ID=${NODE_SMARTLOOK_PROJECT_ID}
ENV NODE_IP_INFO_TOKEN=${NODE_IP_INFO_TOKEN}
ENV NODE_ANALYTICS_UNIVERSAL_KEY=${NODE_ANALYTICS_UNIVERSAL_KEY}
ENV NODE_GA4_KEY=${NODE_GA4_KEY}
ENV NODE_SENDPULSE_ADDRESSBOOKS_ID=${NODE_SENDPULSE_ADDRESSBOOKS_ID}
ENV FF_ENVIRONMENT=${FF_ENVIRONMENT}
ENV RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
ENV MAD_MARKETING_BACKEND_API=${MAD_MARKETING_BACKEND_API}
ENV NUXT_PUBLIC_SITE_URL=${NUXT_PUBLIC_SITE_URL}
ENV NITRO_PRESET=${NITRO_PRESET}
ENV NODE_SENTRY_LOADER_PATH=${NODE_SENTRY_LOADER_PATH}

WORKDIR /app
COPY . /app
RUN npm install && \
    npm cache clean --force

RUN npm run build

ENV PORT 3000
EXPOSE 3000

CMD ["npm", "run", "start"]

