// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from 'vue'
import { defineSliceZoneComponents } from '@prismicio/vue'

export const blogComponents = defineSliceZoneComponents({
  text: defineAsyncComponent(() => import('./BlogText.vue')),
})
