import { config } from 'dotenv'

config()

// Atlassian
export const ATLASSIAN_TOKEN = process.env.NODE_ATLASSIAN_TOKEN
export const ATLASSIAN_EMAIL = process.env.NODE_ATLASSIAN_EMAIL
export const ATLASSIAN_AUTH_TOKEN = `${ ATLASSIAN_EMAIL }:${ ATLASSIAN_TOKEN }`
export const ATLASSIAN_PROJECT_KEY = process.env.NODE_ATLASSIAN_PROJECT_KEY
export const ATLASSIAN_API_URL = process.env.NODE_ATLASSIAN_API_URL
export const ATLASSIAN_PROJECT_EBOOK_KEY = process.env.NODE_ATLASSIAN_EBOOK_PROJECT_KEY
export const ATLASSIAN_SUBSCRIBERS_PROJECT_KEY = process.env.NODE_ATLASSIAN_SUBSCRIBERS_PROJECT_KEY

// Send pulse
export const SENDPULSE_API_KEY = process.env.NODE_SENDPULSE_API_KEY
export const SENDPULSE_API_USER_ID = process.env.NODE_SENDPULSE_API_USER_ID
export const SENDPULSE_TOKEN_STORAGE = '/tmp/'
export const SENDPULSE_ADDRESSBOOKS_FOR_RADIATOR = process.env.NODE_SENDPULSE_ADDRESSBOKS_FOR_RADIATOR

// Sentry
export const SENTRY_DSN = process.env.NODE_SENTRY_DSN

// Other
export const { NODE_ENV } = process.env

// S3
export const S3_ACCESS_KEY_ID = process.env.NODE_S3_ACCESS_KEY_ID
export const S3_SECRET_ACCESS_KEY = process.env.NODE_S3_SECRET_ACCESS_KEY

// IP
export const IP_INFO_TOKEN = process.env.NODE_IP_INFO_TOKEN
export const IP_BAN_LIST = process.env.NODE_IP_BAN_LIST
export const IP_TEST_LIST = process.env.NODE_IP_TEST_LIST
export const TEST_EMAIL = process.env.NODE_TEST_EMAIL

// Prismic
export const PRISMIC_API = process.env.NODE_PRISMIC_API

// reCaptcha key
export const RECAPTCHA_KEY = process.env.RECAPTCHA_SECRET_KEY

// dev Radiator
export const DEV_RADIATOR_SLACK_CHANNEL_ID = process.env.NODE_DEV_RADIATOR_SLACK_CHANNEL_ID
export const { SLACK_WEBHOOK_URL } = process.env
export const DEV_RADIATOR_GH_TOKEN = process.env.NODE_DEV_RADIATOR_GH_TOKEN
export const DEV_RADIATOR_PAGESPEED_MEASUREMENTS_COUNT = process.env.NODE_DEV_RADIATOR_PAGESPEED_MEASUREMENTS_COUNT
export const DEV_RADIATOR_COLLECT_DATA_CRON_STRING = process.env.NODE_DEV_RADIATOR_COLLECT_DATA_CRON_STRING
export const DEV_RADIATOR_SEND_MESSAGE_CRON_STRING = process.env.NODE_DEV_RADIATOR_SEND_MESSAGE_CRON_STRING
export const DEV_RADIATOR_MONGO = process.env.NODE_DEV_RADIATOR_MONGO

export const GOOGLEAPIS_KEY = process.env.NODE_GOOGLEAPIS_KEY

// mad radiator
export const MAD_RADIATOR_AUTH_TYPE = process.env.RADIATOR_AUTH_TYPE
export const MAD_RADIATOR_AUTH_URI = process.env.RADIATOR_AUTH_URI
export const MAD_RADIATOR_CLIENT_CERT_URL = process.env.RADIATOR_CLIENT_CERT_URL
export const MAD_RADIATOR_CLIENT_EMAIL = process.env.RADIATOR_CLIENT_EMAIL
export const MAD_RADIATOR_CLIENT_ID = process.env.RADIATOR_CLIENT_ID
export const MAD_RADIATOR_GOOGLEAPIS_KEY = process.env.NODE_GOOGLEAPIS_KEY
export const MAD_RADIATOR_PRIVATE_KEY = process.env.RADIATOR_PRIVATE_KEY
export const MAD_RADIATOR_PRIVATE_KEY_ID = process.env.RADIATOR_PRIVATE_KEY_ID
export const MAD_RADIATOR_PROJECT_ID = process.env.RADIATOR_PROJECT_ID
export const MAD_RADIATOR_PROVIDER_CERT_URL = process.env.RADIATOR_PROVIDER_CERT_URL
export const MAD_RADIATOR_TOKEN_URI = process.env.RADIATOR_TOKEN_URI
export const MAD_RADIATOR_SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL
export const MAD_RADIATOR_SLACK_CHANNEL_ID = process.env.SLACK_CHANNEL_ID
export const MAD_RADIATOR_REDDIT_CLIENT_ID = process.env.REDDIT_CLIENT_ID
export const MAD_RADIATOR_REDDIT_CLIENT_SECRET = process.env.REDDIT_CLIENT_SECRET
export const MAD_RADIATOR_REDDIT_USER_NAME = process.env.REDDIT_USER_NAME
export const MAD_RADIATOR_REDDIT_PASSWORD = process.env.REDDIT_PASSWORD
export const MAD_RADIATOR_QUORA_USER_ID = process.env.RADIATOR_QUORA_USER_ID
export const MAD_RADIATOR_DAILY_DISPATCH_TIME = process.env.RADIATOR_DAILY_DISPATCH_TIME
export const MAD_RADIATOR_FIRESTORE_AUTH_TYPE = process.env.RADIATOR_FIRESTORE_AUTH_TYPE
export const MAD_RADIATOR_FIRESTORE_PROJECT_ID = process.env.RADIATOR_FIRESTORE_PROJECT_ID
export const MAD_RADIATOR_FIRESTORE_PRIVATE_KEY_ID = process.env.RADIATOR_FIRESTORE_PRIVATE_KEY_ID
export const MAD_RADIATOR_FIRESTORE_PRIVATE_KEY = process.env.RADIATOR_FIRESTORE_PRIVATE_KEY
export const MAD_RADIATOR_FIRESTORE_CLIENT_EMAIL = process.env.RADIATOR_FIRESTORE_CLIENT_EMAIL
export const MAD_RADIATOR_FIRESTORE_CLIENT_ID = process.env.RADIATOR_FIRESTORE_CLIENT_ID
export const MAD_RADIATOR_FIRESTORE_AUTH_URI = process.env.RADIATOR_FIRESTORE_AUTH_URI
export const MAD_RADIATOR_FIRESTORE_TOKEN_URI = process.env.RADIATOR_FIRESTORE_TOKEN_URI
export const MAD_RADIATOR_FIRESTORE_AUTH_PROVIDER = process.env.RADIATOR_FIRESTORE_AUTH_PROVIDER
export const MAD_RADIATOR_FIRESTORE_CLIENT_CERT_URL = process.env.RADIATOR_FIRESTORE_CLIENT_CERT_URL
export const MAD_RADIATOR_TOTAL_USERS_TO_ENJI_URL = process.env.RADIATOR_TOTAL_USERS_TO_ENJI_URL
export const MAD_RADIATOR_GLASSDOOR_API_KEY = process.env.RADIATOR_GLASSDOOR_API_KEY

// to send email from ebook form
export const EMAIL_NODE_EMAIL_MARKETING = process.env.NODE_EMAIL_MARKETING
export const {
  CHECK_MEMORY_USAGE_CRON_STRING,
  CHECK_MEMORY_USAGE_WHEN_ALARM_PERC,
  CHECK_MEMORY_USAGE_ENABLED,
  CHECK_MEMORY_USAGE_SIZE_MEM,
} = process.env

export const { CHECK_PRODUCTION_STATUS_CRON_STRING } = process.env
export const { USERS_TO_BE_MENTIONED } = process.env
export const { SITE_URL_FOR_CHECK } = process.env
export const { SLACK_CHANNEL_ID_FOR_PROD_CHECK } = process.env
export const { MAD_MARKETING_BACKEND_API } = process.env
export const { NODE_EMAIL_CONTACT, NODE_EMAIL_CV } = process.env
export const {
  FF_ENVIRONMENT,
  NODE_EMAIL_MARKETING,
  MOOSEND_API_KEY,
  MOOSEND_MAILING_LIST_ID,
  MOOSEND_HOST_NAME,
  MAD_BACKEND_ACCESS_EMAIL,
  MAD_BACKEND_ACCESS_TOKEN,
  NODE_DOMAIN,
  INTERNAL_BACKEND_ACCESS_TOKEN,
  CIPHER_ALGORITHM,
} = process.env

export const MAD_BACKEND_TOKEN = `${ MAD_BACKEND_ACCESS_EMAIL }:${ MAD_BACKEND_ACCESS_TOKEN }`
export const INTERNAL_BACKEND_TOKEN = `${ MAD_BACKEND_ACCESS_EMAIL }:${ INTERNAL_BACKEND_ACCESS_TOKEN }`

export const { NODE_ATLASSIAN_CAREERS_PROJECT_KEY } = process.env
