<template>
  <section id="privacy">
    <div class="container">
      <div class="privacy__header">
        <h1 class="privacy__title">
          Mad Devs Privacy Policy <br>
          and Terms of Website Use
        </h1>
        <div class="privacy__image" />
      </div>
      <div class="privacy__content">
        <p class="privacy__text privacy__break-main privacy__break-main--first">
          This document explains what information is collected by Mad Devs when you visit the
          maddevs.io website (hereinafter “the website”) or maddevsgroup.co.uk website, visit any related websites
          (hereinafter “subdomains”), use any other services provided by Mad Devs, or communicate with us by any
          means including by email, phone, messenger, or any other medium. This privacy policy also explains how
          you can control the information we collect, how this information will be used, how we protect
          your personal data, and how to contact us.
        </p>
        <p class="privacy__text privacy__break-main">
          We constantly review the content of the privacy policy to reflect current data and processes.
          The latest update was published on April 17, 2023.
        </p>
        <h2 class="privacy__sec-title privacy__sec-title--first">
          Overview
        </h2>
        <p class="privacy__paragraph">
          We respect your privacy and are committed to protecting your personal data. This privacy policy serves
          to inform you of our data protection practices when you visit our website, and of your privacy rights,
          regardless of your location.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          This website is not intended for children and we do not knowingly collect data relating to children.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          It is important that you read this privacy policy together with any other data protection documents we
          may provide on specific occasions when we are collecting or processing personal data about you so that
          you are fully aware of how and why we are using your data. This privacy policy supplements other notices
          and privacy policies and is not intended to override them.
        </p>
        <h2 class="privacy__sec-title">
          Get help
        </h2>
        <p class="privacy__paragraph">
          Our Chief Information Officer Andrew Sapozhnikov is responsible for overseeing questions in relation to
          this privacy policy. If you have any questions about this privacy policy, including any requests to
          exercise your legal rights, please contact the CIO using the email address
          <a
            class="privacy__link"
            href="mailto:rock@maddevs.io"
          >
            rock@maddevs.io
          </a>.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          You have the right to make a complaint at any time to the Information Commissioner's Office (ICO), the UK
          supervisory authority for data protection issues (<a
            class="privacy__link"
            href="https://ico.org.uk/"
            target="_blank"
            rel="noopener"
          >www.ico.org.uk</a>). We would, however, appreciate the
          chance to deal with your concerns before you approach the ICO so please contact us in the first instance.
        </p>
        <h2 class="privacy__sec-title">
          Glossary
        </h2>
        <p class="privacy__paragraph privacy__break">
          Please use the Glossary to understand the meaning of some of the terms used in this privacy policy.
        </p>
        <div class="privacy__term-container">
          <div class="privacy__term-title">
            Personal Data
          </div>
          <div class="privacy__term-description">
            Personal data refers to any information that can directly or indirectly identify a person, such as
            a name, email address, phone number, address, location data, online identifiers, and IP addresses.
          </div>
        </div>
        <div class="privacy__term-container">
          <div class="privacy__term-title">
            Usage Data
          </div>
          <div class="privacy__term-description">
            Usage Data is data collected automatically either generated by browsing our site or from our service
            infrastructure itself (for example, the duration of a page visit).
          </div>
        </div>
        <div class="privacy__term-container">
          <div class="privacy__term-title">
            Data Controller
          </div>
          <div class="privacy__term-description">
            Data Controller means the natural or legal person who (either alone or jointly or in
            common with other persons) determines the purposes for which and the manner in which any
            personal information is, or is to be, processed. For the purpose of this Privacy Policy,
            we are the Data Controller of your Personal Data.
          </div>
        </div>
        <div class="privacy__term-container">
          <div class="privacy__term-title">
            Data Processors (or Service Providers)
          </div>
          <div class="privacy__term-description">
            Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf
            of the Data Controller. We may use the services of various service providers in order to process your
            data more effectively.
          </div>
        </div>
        <div class="privacy__term-container">
          <div class="privacy__term-title">
            Data Subject (or User)
          </div>
          <div class="privacy__term-description">
            Data Subject is any living individual who is using our service and is the subject of Personal Data.
          </div>
        </div>
        <div class="privacy__term-container">
          <div class="privacy__term-title">
            Information Collection and Use
          </div>
          <div class="privacy__term-description">
            We collect several different types of information for various purposes to provide and improve our service to you.
          </div>
        </div>
        <h2 class="privacy__sec-title">
          1. Who we are
        </h2>
        <p class="privacy__paragraph">
          We are Mad Devs Group Ltd. (hereinafter “we”). We are registered in England and Wales under company number
          11793394 and have our registered office at 27 Old Gloucester Street, London, United Kingdom, WC1N 3AX.
          We also have close associations with Mad Devs LLC, a company registered in Kyrgyzstan under company
          number 02004201710239, and have a registered office at 103 Ibraimova Str., Bishkek, 720011, Kyrgyz Republic.
        </p>
        <h2 class="privacy__sec-title">
          2. By using our website you accept these terms
        </h2>
        <p class="privacy__paragraph">
          By using our site, you confirm that you accept the terms of this policy and that you agree to comply with them.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          If you do not agree to these terms, you must not use our site.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          We recommend that you print a copy of these terms for future reference.
        </p>
        <h2 class="privacy__sec-title">
          3. About the data we collect
        </h2>
        <h3 class="privacy__sec-title privacy__sec-title--medium privacy__sec-title--multi-title">
          3.1. Data we collect
        </h3>
        <h4 class="privacy__sec-title privacy__sec-title--xs privacy__sec-title--multi-title">
          Personal Data
        </h4>
        <p class="privacy__paragraph">
          While using our service, we may ask you to provide us with certain personally identifiable information that
          can be used to contact or identify you (“Personal Data”). Personally identifiable information
          may include but is not limited to:
        </p>
        <ul class="privacy__list-wrap">
          <li class="privacy__list">
            Email address,
          </li>
          <li class="privacy__list">
            First name and last name,
          </li>
          <li class="privacy__list">
            Phone number.
          </li>
        </ul>
        <p class="privacy__paragraph privacy__paragraph-margin">
          We collect and store IP addresses when you visit our website, but we do not actively use them for any
          specific purpose, except analytics and website security. Please be aware that we may disclose your
          IP address in situations where we are required to do so by law or where it is necessary
          to protect our legal rights or the rights of others.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          3.2. How we use the data
        </h3>
        <p class="privacy__paragraph">
          Mad Devs Group Ltd. uses the collected data for various purposes:
        </p>
        <ul class="privacy__list-wrap">
          <li class="privacy__list">
            To provide and maintain our service,
          </li>
          <li class="privacy__list">
            To notify you about changes to our service,
          </li>
          <li class="privacy__list">
            To allow you to participate in interactive features of our service when you choose to do so,
          </li>
          <li class="privacy__list">
            To provide customer support,
          </li>
          <li class="privacy__list">
            To gather analysis or valuable information so that we can improve our service,
          </li>
          <li class="privacy__list">
            To monitor the usage of our service,
          </li>
          <li class="privacy__list">
            To detect, prevent and address technical issues.
          </li>
        </ul>
        <h4 class="privacy__sec-title privacy__sec-title--xs">
          Legal Basis for Processing Personal Data under the General Data Protection Regulation
          (<NuxtLink
            to="/gdpr/"
            class="privacy__sec-title--link"
          >
            GDPR
          </NuxtLink>)
        </h4>
        <p class="privacy__paragraph">
          If you are from the European Economic Area (EEA), Mad Devs Group Ltd's legal basis for collecting and using
          the personal information described in this privacy policy depends on the Personal Data we collect
          and the specific context in which we collect it.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Mad Devs Group Ltd. may process your Personal Data because:
        </p>
        <ul class="privacy__list-wrap">
          <li class="privacy__list">
            We need to perform a contract with you,
          </li>
          <li class="privacy__list">
            You have given us permission to do so,
          </li>
          <li class="privacy__list">
            The processing is in our legitimate interests and it is not overridden by your rights,
          </li>
          <li class="privacy__list">
            To comply with the law.
          </li>
        </ul>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          3.3. Retention of Data
        </h3>
        <p class="privacy__paragraph">
          Mad Devs Group Ltd. will retain your Personal Data only for as long as is necessary for the purposes
          set out in this privacy policy. We will retain and use your Personal Data to the extent
          necessary to comply with our legal obligations (for example, if we are required to retain your data
          to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Mad Devs Group Ltd. will also retain Usage Data for internal analysis purposes. Usage Data is generally
          retained for a shorter period of time, except when this data is used to strengthen the security or
          to improve the functionality of our service, or we are legally obligated to retain this data for longer periods.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          3.4. Transfer of Data
        </h3>
        <p class="privacy__paragraph">
          We share your personal data within Mad Devs companies. This will involve transferring your data
          outside the European Economic Area (EEA).
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          We ensure your personal data is protected by requiring all our group companies to follow the same
          rules when processing your personal data.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Whenever we transfer your personal data out of the EEA, we ensure a similar degree of protection is
          afforded to it by ensuring at least one of the following safeguards is implemented.
          We will only transfer your personal data to countries that have been deemed to provide an adequate
          level of protection for personal data by the European Commission. For further details, see
          <a
            class="privacy__link"
            href="https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/adequacy-decisions_en"
            target="_blank"
            rel="noopener"
          >
            European Commission: Adequacy of the protection of personal data in non-EU countries
          </a>.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Where we use certain service providers, we may use specific contracts approved by the European
          Commission which give personal data the same protection it has in Europe. For further details, see
          <a
            class="privacy__link"
            href="https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en"
            target="_blank"
            rel="noopener"
          >
            European Commission: Model contracts for the transfer of personal data to third countries
          </a>.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Where we use providers based in the US, we may transfer data to them if they are part of the Privacy Shield
          which requires them to provide similar protection to personal data shared between Europe and the US.
          For further details, see
          <a
            class="privacy__link"
            href="https://commission.europa.eu/law/law-topic/data-protection/international-dimension-data-protection/eu-us-data-transfers_en"
            target="_blank"
            rel="noopener"
          >
            European Commission: EU-US Privacy Shield
          </a>.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          3.5. Marketing
        </h3>
        <p class="privacy__paragraph">
          We strive to provide you with choices regarding certain personal data uses, particularly around marketing and advertising.
        </p>
        <h4 class="privacy__sec-title privacy__sec-title--xs privacy__sec-title--multi-title">
          Promotional offers from us
        </h4>
        <p class="privacy__paragraph">
          We may use your identity, contact details, and information we hold about you to form a view on what we
          think you may want or need, or what may be of interest to you. This is how we decide which products,
          services, and offers may be relevant for you (we call this marketing).
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          You will receive marketing communications from us if you have requested information from us or
          purchased services from us and you have not opted out of receiving that marketing.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          3.6. Change of purpose
        </h3>
        <p class="privacy__paragraph">
          We will only use your personal data for the purposes for which we collected it unless we reasonably
          consider that we need to use it for another reason and that reason is compatible with the original purpose.
          If you wish to get an explanation as to how the processing for the new purpose is
          compatible with the original purpose, please contact us.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          If we need to use your personal data for an unrelated purpose, we will notify you and we will explain
          the legal basis which allows us to do so.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Please note that we may process your personal data without your knowledge or consent, in compliance with the
          above rules, where this is required or permitted by law.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          3.7. Disclosure of Data
        </h3>
        <h4 class="privacy__sec-title privacy__sec-title--xs privacy__sec-title--multi-title">
          Disclosure for Law Enforcement
        </h4>
        <p class="privacy__paragraph">
          Under certain circumstances, Mad Devs Group Ltd. may be required to disclose your Personal Data if
          required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
        </p>
        <h4 class="privacy__sec-title privacy__sec-title--xs privacy__sec-title--multi-title">
          Legal Requirements
        </h4>
        <p class="privacy__paragraph">
          Mad Devs Group Ltd. may disclose your Personal Data in limited circumstances if such action is necessary to as follows:
        </p>
        <ul class="privacy__list-wrap">
          <li class="privacy__list">
            To comply with a legal obligation,
          </li>
          <li class="privacy__list">
            To protect and defend the rights or property of Mad Devs Group Ltd.,
          </li>
          <li class="privacy__list">
            To prevent or investigate possible wrongdoing in connection with our service,
          </li>
          <li class="privacy__list">
            To protect the personal safety of users of our service or the public,
          </li>
          <li class="privacy__list">
            To protect against legal liability.
          </li>
        </ul>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          3.8. Security of Data
        </h3>
        <p class="privacy__paragraph">
          We have put in place appropriate security measures to prevent your personal data from being accidentally
          lost, used, or accessed in an unauthorized way, altered, or disclosed. In addition, we limit
          access to your personal data to those employees, agents, contractors, and other third parties who have
          a business need to know. They will only process your personal data on our
          instructions and they are subject to a duty of confidentiality.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          We have put in place procedures to deal with any suspected personal data breach and will notify you and
          any applicable regulator of a breach where we are legally required to do so.
        </p>
        <h2 class="privacy__sec-title">
          4. Your rights
        </h2>
        <p class="privacy__paragraph">
          The right to access, update or delete the information we have on you. Whenever made possible, you can access,
          update, or request the deletion of your Personal Data directly within your account settings section.
          If you are unable to perform these actions yourself, please contact us to assist you.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          <strong>The right of rectification.</strong> You have the right to have your information rectified if
          that information is inaccurate or incomplete.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          <strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          <strong>The right of restriction.</strong> You have the right to request that we restrict the
          processing of your personal information.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          <strong>The right to data portability.</strong> You have the right to be provided with a copy of the
          information we have on you in a structured, machine-readable, and commonly used format.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          <strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any
          time when Mad Devs Group Ltd. relies on your consent to process your personal information.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Please note that we may ask you to verify your identity before responding to such requests.
          You have the right to complain to a Data Protection Authority about our collection and use of your
          Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          No fee is usually required
        </h3>
        <p class="privacy__paragraph">
          You will not have to pay a fee to access your personal data (or to exercise any of the other rights).
          However, we may charge a reasonable fee if your request is clearly unfounded, repetitive, or excessive.
          Alternatively, we could refuse to comply with your request in these circumstances.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          What we may need from you
        </h3>
        <p class="privacy__paragraph">
          We may need to request specific information from you to help us confirm your identity and ensure your right
          to access your personal data (or to exercise any of your other rights). This is a security measure to
          ensure that personal data is not disclosed to any person who has no right to receive it.
          We may also contact you to ask you for further information in relation to your request to speed up our response.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          Time limit to respond
        </h3>
        <p class="privacy__paragraph">
          We try to respond to all legitimate requests within one month. Occasionally it could take us longer
          than a month if your request is particularly complex or you have made a number of requests.
          In this case, we will notify you and keep you updated.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          Your Data Protection Rights under the General Data Protection Regulation
          (<NuxtLink
            to="/gdpr/"
            class="privacy__sec-title--link privacy__sec-title--link-red"
          >
            GDPR
          </NuxtLink>)
        </h3>
        <p class="privacy__paragraph">
          If you are a resident of the European Economic Area (EEA), you have certain data protection rights.
          Mad Devs Group Ltd. aims to take reasonable steps to allow you to correct, amend,
          delete, or limit the use of your Personal Data.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          If you wish to be informed about what Personal Data we hold about you and if you want it to be
          removed from our systems, please contact us at <a
            class="privacy__link"
            href="mailto:rock@maddevs.io"
          >
            rock@maddevs.io
          </a>.
        </p>
        <h2 class="privacy__sec-title">
          5. Cookie Policy
        </h2>
        <p class="privacy__paragraph">
          Our website uses cookies to distinguish you from other users of our website. This helps us to provide
          you with a good experience when you browse our website and also allows us to improve our site.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          A cookie is a small file of letters and numbers that we store on your browser or the hard drive of your
          computer if you agree. Cookies contain information that is transferred to your computer's hard drive.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          We use the following cookies:
        </h3>
        <p class="privacy__paragraph">
          Strictly necessary cookies. These are cookies that are required for the operation of our website.
          Analytical or performance cookies. These allow us to recognize and count the number of visitors and to see
          how visitors move around our website when they are using it. This helps us to improve the way our
          website works, for example, by ensuring that users are finding what they are looking for easily.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          Google Analytics
        </h3>
        <p class="privacy__paragraph">
          Google Analytics is a web analytics service offered by Google that tracks and reports website traffic.
          Google uses the data collected to track and monitor the use of our Service. This data is shared with
          other Google services. Google may use the collected data to contextualize and personalize the ads
          of its own advertising network. You can opt out of having made your activity on the Service available
          to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents
          the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing
          information with Google Analytics about visits activity.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          For more information on the privacy practices of Google, please visit the Google Privacy Terms web page:
          <a
            class="privacy__link"
            href="https://policies.google.com/privacy?hl=en"
            target="_blank"
            rel="noopener"
          >
            https://policies.google.com/privacy?hl=en
          </a>
        </p>
        <ul class="privacy__list-wrap">
          <li class="privacy__list">
            Functionality cookies. These are used to recognize you when you return to our website. This enables us to
            personalize our content for you, greet you by name, and remember your
            preferences (for example, your choice of language or region).
          </li>
          <li class="privacy__list">
            Targeting cookies. These cookies record your visit to our website, the pages you have visited,
            and the links you have followed. We will use this information to make our website and the advertising
            displayed on it more relevant to your interests.
          </li>
        </ul>
        <p class="privacy__paragraph privacy__paragraph-margin">
          You can block cookies by activating the setting on your browser that allows you to refuse the setting of
          all or some cookies. However, if you use your browser settings to block all cookies
          (including essential cookies) you may not be able to access all or parts of our website.
        </p>
        <h3 class="privacy__sec-title privacy__sec-title--medium">
          Smartlook
        </h3>
        <p class="privacy__paragraph">
          Smartlook is a web analytics service that helps us understand how visitors interact with our website.
          Smartook processes only the personal data that you provide to us. To make sure it is adequately
          protected, we enter into Data Processing Agreements with Smartlook.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Smartlook is contractually obligated to comply with all applicable data protection laws and to use any
          personal data collected only for the purposes of providing us with their services.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          If you don't want to be recorded by Smartlook, you can
          <a
            class="privacy__link"
            href="https://www.smartlook.com/opt-out/"
            target="_blank"
            rel="noopener"
          >
            opt out here.
          </a> Please note that if you clear your
          cookies or use a different browser, you will need to opt out again. For more information
          about how Smartlook uses your data, please visit the website:
          <a
            class="privacy__link"
            href="https://help.smartlook.com/docs/privacy-policy"
            target="_blank"
            rel="noopener"
          >
            https://help.smartlook.com/docs/privacy-policy.
          </a>
        </p>
        <h2 class="privacy__sec-title">
          6. Service Providers
        </h2>
        <p class="privacy__paragraph">
          We may employ third-party companies and individuals to facilitate our Service ("Service Providers"),
          provide the Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          These third parties have access to your Personal Data only to perform these tasks on our behalf and are
          obligated not to disclose or use it for any other purpose.
        </p>
        <h2 class="privacy__sec-title">
          7. Links to Other Sites
        </h2>
        <p class="privacy__paragraph">
          Our Service may contain links to other sites that are not operated by us. If you click a third-party link,
          you will be directed to that third party's site. We strongly advise you to review the Privacy Policy
          of every site you visit. We have no control over and assume no responsibility for any third-party
          sites or services' content, privacy policies, or practices.
        </p>
        <h2 class="privacy__sec-title">
          8. Prohibited uses
        </h2>
        <p class="privacy__paragraph">
          You may use our site only for lawful purposes. You may not use our site:
        </p>
        <ul class="privacy__list-wrap">
          <li class="privacy__list">
            In any way that breaches any applicable local, national, or international law or regulation.
          </li>
          <li class="privacy__list">
            In any way that is unlawful or fraudulent or has any unlawful or fraudulent purpose or effect.
          </li>
          <li class="privacy__list">
            To transmit, or procure the sending of, any unsolicited or unauthorized advertising or promotional
            material or any other form of similar solicitation (spam).
          </li>
          <li class="privacy__list">
            To knowingly transmit any data, send or upload any material that contains viruses, Trojan horses, worms,
            time-bombs, keystroke loggers, spyware, adware, or any other harmful programs or similar computer
            code designed to adversely affect the operation of any computer software or hardware.
          </li>
        </ul>
        <p class="privacy__paragraph privacy__paragraph-margin">
          You also agree not to reproduce, duplicate, copy, or re-sell any part of our site in contravention
          of the provisions of our terms of website use. Not to access without authority, interfere with,
          damage or disrupt any part of our site, any equipment or network on which our site is stored,
          any software used in the provision of our site, or any equipment or network or software owned or used by any third party.
        </p>
        <h2 class="privacy__sec-title">
          9. Breach of this policy
        </h2>
        <p class="privacy__paragraph">
          When we consider that a breach of this acceptable use policy has occurred, we may take such action as we deem appropriate.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          Failure to comply with this acceptable use policy constitutes a material breach of the terms of use
          upon which you are permitted to use our site, and may result in our taking all or any of the following actions:
        </p>
        <ul class="privacy__list-wrap">
          <li class="privacy__list">
            Immediate, temporary, or permanent withdrawal of your right to use our site.
          </li>
          <li class="privacy__list">
            Issue of a warning to you.
          </li>
          <li class="privacy__list">
            Legal action against you.
          </li>
          <li class="privacy__list">
            Disclosure of such information to law enforcement authorities as we reasonably feel is necessary or as required by law.
          </li>
        </ul>
        <p class="privacy__paragraph privacy__paragraph-margin">
          We exclude our liability for all actions we may take in response to breaches of this acceptable use policy.
          The actions we may take are not limited to those described above, and we may take any other action
          we reasonably deem appropriate.
        </p>
        <h2 class="privacy__sec-title">
          10. Which country's laws apply to any disputes?
        </h2>
        <p class="privacy__paragraph">
          If you are a consumer, please note that the terms of this policy, its subject matter, and its formation are
          governed by English law. You and we both agree that the courts of England and Wales will have exclusive jurisdiction.
        </p>
        <p class="privacy__paragraph privacy__paragraph-margin">
          If you are a business, the terms of this policy, its subject matter, and its formation
          (and any non-contractual disputes or claims) are governed by English law. We both agree
          to the exclusive jurisdiction of the courts of England and Wales.
        </p>
      </div>
    </div>
  </section>
</template>
<style lang="scss" scoped>
.privacy {
  width: 100%;
  height: 100%;
  position: relative;
  background-color: $bgcolor--black;

  &__header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-top: 71px;
  }

  &__content {
    max-width: 880px;
  }

  &__paragraph,
  &__list-wrap,
  &__term-title,
  &__term-description {
    color: $remote-tech-staff-sub-title-grey;
  }

  &__paragraph {
    @include font('Inter', 17px, 400);
    line-height: 28px;
    letter-spacing: -0.02em;
  }

  &__paragraph-margin {
    margin-top: 14px;
  }

  &__list-wrap {
    margin: 14px 0;
  }

  &__list {
    display: flex;
    list-style: none;
    margin-bottom: 10px;

    &::before {
      margin-right: 15px;
      content: '\2022';
    }
  }

  &__title,
  &__text,
  &__link {
    color: $text-color--white;
  }

  &__title {
    @include h2-title;
    @include font('Inter', 62px, 700);
    padding-top: 146px;

    @media screen and (max-width: 834px) {
      padding-top: 122px;
    }

    @media screen and (max-width: 578px) {
      padding-top: 98px;
    }
  }

  &__sec-title {
    @include font('Inter', 24px, 400);
    margin-top: 48px;
    margin-bottom: 8px;
    line-height: 136%;
    letter-spacing: 0;
    color: $text-color--red;

    &--first {
      margin-top: 71px;
    }

    &--italic {
      font-style: italic;
    }

    &--multi-title {
      margin-top: 15px;
    }

    &--medium {
      font-size: 22px;
    }

    &--xs {
      font-size: 18px;
      color: $remote-tech-staff-sub-title-grey;
      font-weight: 700;
    }

    &--link {
      color: $remote-tech-staff-sub-title-grey;
      text-decoration: underline;

      &-red {
        color: $text-color--red;
      }
    }
  }

  &__term-container {
    display: flex;
    justify-content: space-between;
    margin-top: 15px;
    margin-bottom: 15px;
  }

  &__term-title {
    width: 20%;
    font-weight: bold;
  }

  &__term-description {
    width: 75%;
  }

  &__break {
    margin-bottom: 5px;
  }

  &__link {
    text-decoration: none;
  }

  &__break-main {
    @include font('Inter', 22px, 400);
    margin: 25px 0;
    font-size: 22px;
    line-height: 36px;
    letter-spacing: -0.035em;

    &--first {
      margin-top: 0;
    }

    @media only screen and (max-width: 350px) {
      font-size: 20px;
    }
  }

  &__nowrap {
    white-space: nowrap;
  }

  &__image {
    width: 190px;
    height: 230px;
    display: block;
    position: relative;
    top: 80px;
    @include document-icon;

    @media only screen and (max-width: 1300px) {
      width: 140px;
      height: 170px;
      top: 55px;
    }

    @media only screen and (max-width: 1200px) {
      width: 100px;
      height: 150px;
      top: 30px;
    }
  }

  @media only screen and (max-width: 1060px) {
    &__image {
      display: none;
    }

    &__title {
      br {
        display: none;
      }
    }
  }

  @media only screen and (max-width: 768px) {
    &__term-container {
      flex-direction: column;
    }

    &__term-title {
      width: 100%;
      margin-top: 20px;
      margin-bottom: 5px;
    }

    &__term-description {
      width: 100%;
    }
  }
}
</style>
