// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from 'vue'
import { defineSliceZoneComponents } from '@prismicio/vue'

export const components = defineSliceZoneComponents({
  spacer_slice: defineAsyncComponent(() => import('./SpacerSlice/index.vue')),
  start_screen: defineAsyncComponent(() => import('./StartScreen/index.vue')),
  tabs_slice: defineAsyncComponent(() => import('./TabsSlice/index.vue')),
  title_and_description: defineAsyncComponent(() => import('./TitleAndDescription/index.vue')),
  industries: defineAsyncComponent(() => import('./Industries/index.vue')),
  customers_slice: defineAsyncComponent(() => import('./CustomersSlice/index.vue')),
  customers_card_slice: defineAsyncComponent(() => import('./CustomersCardSlice/index.vue')),
  customer_rates_slice: defineAsyncComponent(() => import('./CustomerRatesSlice/index.vue')),
  key_metrics_slice: defineAsyncComponent(() => import('./KeyMetricsSlice/index.vue')),
  cta_banner_slice: defineAsyncComponent(() => import('./CtaBannerSlice/index.vue')),
})
