name: Staging deployment

on:
  push:
    branches:
      - staging
      - develop

jobs:
  build:
    runs-on: ${{ vars.ACTIVE_RUNNER }}

    steps:
    - name: Prepare variables
      run: |
            echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        build-args: |
          NODE_ENV=${{ secrets.STAGING_NODE_ENV }}
          NODE_S3_PUBLIC_URL=${{ secrets.STAGING_NODE_S3_PUBLIC_URL }}
          NODE_DOMAIN=${{ secrets.STAGING_NODE_DOMAIN }}
          NODE_EMAIL_HR=${{ secrets.STAGING_NODE_EMAIL_HR }}
          NODE_EMAIL_CV=${{ secrets.STAGING_NODE_EMAIL_CV }}
          NODE_EMAIL_CONTACT=${{ secrets.STAGING_NODE_EMAIL_CONTACT }}
          NODE_EMAIL_MARKETING=${{ secrets.STAGING_NODE_EMAIL_MARKETING }}
          NODE_SENTRY_DSN_FRONT=${{ secrets.STAGING_NODE_SENTRY_DSN_FRONT }}
          NODE_PRISMIC_API=${{ secrets.STAGING_NODE_PRISMIC_API }}
          NODE_IP_INFO_TOKEN=${{ secrets.STAGING_NODE_IP_INFO_TOKEN }}
          NODE_SMARTLOOK_PROJECT_ID=${{ secrets.STAGING_NODE_SMARTLOOK_PROJECT_ID }}
          NODE_ANALYTICS_UNIVERSAL_KEY=${{ secrets.STAGING_NODE_ANALYTICS_UNIVERSAL_KEY }}
          NODE_GA4_KEY=${{ secrets.STAGING_NODE_GA4_KEY }}
          NODE_SENDPULSE_ADDRESSBOOKS_ID=${{ secrets.STAGING_NODE_SENDPULSE_ADDRESSBOOKS_ID }}
          FF_ENVIRONMENT=${{ secrets.STAGING_FF_ENVIRONMENT }}
          RECAPTCHA_SITE_KEY=${{ secrets.STAGING_RECAPTCHA_SITE_KEY }}
          MAD_MARKETING_BACKEND_API=${{ secrets.STAGING_MAD_MARKETING_BACKEND_API }}
        cache-from: |
          maddevsio/maddevsio:staging
        tags: maddevsio/maddevsio:staging,maddevsio/maddevsio:${{ env.SHORT_SHA }}

    #--------Uncomment when all packages/dependencies have been updated and vulnerabilities fixed--------#

    # - name: Run Snyk to check Docker image for vulnerabilities
    #   continue-on-error: true
    #   uses: snyk/actions/docker@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     image: maddevsio/maddevsio:${{ env.SHORT_SHA }}

    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@v1.1.4 # replace this with current version from https://github.com/digitalocean/app_action/releases
      with:
        app_name: maddevs-co
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images: '[
              {
                "name": "maddevs",
                "image":{
                  "registry_type": "DOCKER_HUB",
                  "registry": "maddevsio",
                  "repository": "maddevsio",
                  "tag": "${{ env.SHORT_SHA }}"
                }
              }
            ]'
